### ISSUE TITLE
Other editors (neovim, helix, emacs etc.)

### ISSUE THREAD

**Issue by peter-lejon-v** [redhat-developer/quarkus-ls#986]
I'm trying to figure out how to get qute-ls to work for template files with helix. I'm not sure what I'm doing wrong.

this is my configuration for reference:

```toml
[language-server.qute-ls]
command = "java"
args = [
  "-jar",
  "/home/myname/git/github/quarkus-ls/qute.ls/com.redhat.qute.ls/target/com.redhat.qute.ls-uber.jar",
]

[language-server.qute-ls.config.qute]
validation = { enabled = true }
```

and 

```toml
[[language]]
name = "html"
language-servers = ["qute-ls", "tailwindcss-ls", "vscode-html-language-server"]
roots = ["pom.xml", "build.gradle", "build.gradle.kts"]
```

I get this error:

```
helix_term::application [ERROR] Language Server: Method qute/template/project not found in request
helix_lsp::transport [ERROR] qute-ls <- MethodNotFound: Method not found: qute/template/project
```

- I don't know if I'm missing something? 
- Is this the correct way of starting up the ls? Getting jdtls working with java is no problem. 
- Is there perhaps some documentation I can look into?
- How do I use quarkus ls? Can I just replace jdtls, or do I need to run both servers?
- Is there any release of the uber jars? (build-all script is not working for me)

openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

Linux 6.10.6-10-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:17:40 UTC 2024 x86_64 GNU/Linux
